### ISSUE TITLE
Not updating!

### ISSUE THREAD

**Issue by simon-e3** [andyault/sketch-adjusttofit#2]
<img width="492" alt="screen shot 2018-09-05 at 14 56 48" src="https://user-images.githubusercontent.com/10612344/45097985-f3f5b680-b11b-11e8-889d-c6605492dd3c.png">

Won't let me update, the notification is really annoying me! 😂

**Comment by andyault** [comment]
Hey, first off, thanks for the support :)

Unfortunately, I seem to have messed something up with publishing the last update, and I think that the only fix is to delete the plugin and reinstall from the [releases page](https://github.com/andyault/sketch-adjusttofit/releases).

Sorry for the inconvenience, and let me know if there's any other problems/requests you may have!

Thanks!

**Comment by andyault** [comment]
addressed in #3, and fixed in [v1.2.2](https://github.com/andyault/sketch-adjusttofit/releases/tag/v1.2.2)!
